### ISSUE TITLE
让我在游戏内输入bob locale能搜到贵mod吧

### ISSUE THREAD

**Issue by heroboy** [Sraw/modslocale#2]

**Comment by Sraw** [comment]
你好，游戏里应该是能搜到的，只是名字叫：Locale Translations For Bob's Mods

**Comment by heroboy** [comment]
我知道叫这个名字。但是作为翻译bob的mod，我首先想到的关键字是bob locale，用这个关键字是搜不到的。

**Comment by Sraw** [comment]
你好，我稍微研究了一下这个问题。这个问题可以被优化，但游戏中搜索的方式可能和你想象的不太一样。
游戏并不支持多关键字搜索，而是全文匹配搜索，也就是说搜索"bob locale"只能搜到描述中明确包含"bob locale"字段的Mod。

我会在后续的版本中尝试加入SEO优化。谢谢反馈。

**Comment by Sraw** [comment]
Closed #3
